"""SBayesRC for the 3kRG grain weight + shape rerun (Phase G of v0.1.4).

This script is the scaffold for adding SBayesRC \cite{zheng2024leveraging} as
the 6th fine-mapping method on the rice grain pass. SBayesRC requires a
species-specific HM3-substitute LD reference (eigen-decomposed per block).
The public SBayesRC LD reference is human HM3-EUR; we therefore need to build
a 3kRG-specific reference.

There are two paths:

PATH A (canonical, requires gctb binary):
    The standard SBayesRC LD-ref pipeline is:
        SBayesRC::LDstep1(mafile, genoPrefix, outDir, blockRef=...)
            → calls `gctb --bfile ... --extract ... --make-full-ldm` per block
        SBayesRC::LDstep2(outDir, blockIndex)
            → runs the gctb commands generated by LDstep1
        SBayesRC::LDstep3(outDir, blockIndex, thresh=0.995)
            → eigen-decomposes each block's `b{N}.ldm.bin`
        SBayesRC::LDstep4(outDir)
            → merges per-block files into the final LD reference

    Requirements:
        1. Install gctb 2.05beta (binary download from cnsgenomics.com).
        2. Provide a rice block-reference TSV (chr, start_bp, end_bp). Niu 2021
           reports rice-3kRG LD half-decay at ~300 kb (whole population), so a
           300-500 kb block size is appropriate.
        3. ~1300 blocks × ~5-15 min/block ≈ 100-300 CPU-hours total. A targeted
           41-block subset (only the fine-mapped loci windows) is ~3-10 h.

PATH B (gctb-free reproduction, this scaffold):
    Compute LD per block in pure Python from the 3kRG VCF, eigen-decompose,
    and write the SBayesRC binary format directly. Bypasses gctb entirely.

    Per-block, write the four files SBayesRC reads at the `sbayesrc()` step:
        - block{N}.eigen.bin    (header: m, k, lambdaSum, thresh; then top-k
                                 eigenvalues then top-k eigenvectors col-major;
                                 all float32)
        - ldm.info              (Block, Chrom, StartSnpIdx, StartSnpID,
                                 EndSnpIdx, EndSnpID, NumSnps)
        - snp.info              (Chrom, ID, Index, GenPos, PhysPos, A1, A2,
                                 A1Freq, N, Block)

    The .eigen.bin layout is (verified from SBayesRC::LDstep3 source):
        int32  m          — number of markers in the block
        int32  k          — number of retained eigenvectors at thresh
        float32 lambdaSum — sum of positive eigenvalues
        float32 thresh    — variance retention threshold (0.995 by default)
        float32[k] lambda — top-k eigenvalues (descending)
        float32[k][m] V   — top-k eigenvectors, written column-by-column

After the LD reference is built (either path), call:
    SBayesRC::sbayesrc(mafile, LDdir, outPrefix)
to obtain per-variant posterior effect sizes and (downstream) PIPs.

USAGE (Path B, after this scaffold is fleshed out):
    python tests/rice3k_grain_shape_sbayesrc.py --build-ld         # ~10 h
    python tests/rice3k_grain_shape_sbayesrc.py --run-trait TGW
    python tests/rice3k_grain_shape_sbayesrc.py --run-trait GL
    python tests/rice3k_grain_shape_sbayesrc.py --run-trait GW
    python tests/rice3k_grain_shape_sbayesrc.py --run-trait RLW
    python tests/rice3k_grain_shape_sbayesrc.py --collect

This file is a *scaffold* — the LD construction loop is sketched but not yet
wired to the bcftools streaming we use in finemap_v2. Production-ready
implementation is queued for the v0.1.5 revision pass.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np
import pandas as pd

DATA = Path("/mnt/data/GraphGWAS/data/rice_3k")
SBAYES_DIR = DATA / "sbayesrc_rice"
SBAYES_DIR.mkdir(parents=True, exist_ok=True)
RICE_VCF = "/mnt/data/GraphPop/data/raw/3kRG_data/NB_final_snp.vcf.gz"

# Niu 2021 reports rice-3kRG LD half-decay at ~300 kb (whole population).
# 500 kb blocks balance signal capture and tractability.
BLOCK_BP = 500_000


def write_eigen_bin(path: Path, lambdas: np.ndarray, vectors: np.ndarray,
                    lambda_sum: float, thresh: float = 0.995):
    """Write SBayesRC's per-block eigen.bin format.

    Format (verified against SBayesRC::LDstep3, R 4.5.2 + SBayesRC v0.2.6):
        int32  m
        int32  k
        float32 lambdaSum
        float32 thresh
        float32[k] lambda  (descending)
        float32[k][m] V    (column-major, top-k eigenvectors)
    """
    m, k = vectors.shape[0], len(lambdas)
    with open(path, "wb") as fh:
        fh.write(struct.pack("<i", m))
        fh.write(struct.pack("<i", k))
        fh.write(struct.pack("<f", float(lambda_sum)))
        fh.write(struct.pack("<f", float(thresh)))
        np.asarray(lambdas, dtype=np.float32).tofile(fh)
        # column-major: write each eigenvector column as a contiguous block
        for j in range(k):
            np.asarray(vectors[:, j], dtype=np.float32).tofile(fh)


def define_blocks_for_chr(chr_max_bp: int, block_bp: int = BLOCK_BP) -> list[tuple[int, int]]:
    """Non-overlapping fixed-size blocks covering [1, chr_max_bp]."""
    blocks = []
    start = 1
    while start <= chr_max_bp:
        end = min(start + block_bp - 1, chr_max_bp)
        blocks.append((start, end))
        start = end + 1
    return blocks


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-ld", action="store_true",
                    help="Build the rice-3kRG eigen-decomposed LD reference (Path B). "
                         "Long-running (~10 hours; one block at a time).")
    ap.add_argument("--run-trait",
                    help="Run SBayesRC on one of TGW/GL/GW/RLW after the LD ref exists.")
    ap.add_argument("--collect", action="store_true",
                    help="Aggregate the per-trait SBayesRC PIPs at the 41 fine-mapped loci.")
    args = ap.parse_args()

    if not (args.build_ld or args.run_trait or args.collect):
        print(__doc__)
        return

    if args.build_ld:
        print("[Path B] LD-reference construction stub. Production wiring pending.")
        print("This script currently writes only the snp.info + ldm.info skeleton; the "
              "per-block eigen.bin loop must be wired to a bcftools-stream genotype "
              "loader matching the format used in tests/rice3k_grain_shape_finemap.py.")
        # Skeleton: emit the block layout TSV the user can inspect before committing
        # the ~10-hour eigen build.
        # For simplicity, use plink2 .pvar to enumerate variants per block.
        pvar = pd.read_csv(DATA / "rice_3k.pvar", sep="\t", comment="#",
                           names=["#CHROM", "POS", "ID", "REF", "ALT"], low_memory=False)
        pvar["#CHROM"] = pvar["#CHROM"].astype(str)
        rows = []
        idx_global = 0
        block_n = 0
        for chrom_n in range(1, 13):
            sub = pvar[pvar["#CHROM"] == str(chrom_n)].copy()
            if sub.empty:
                continue
            chr_max = int(sub["POS"].max())
            for start, end in define_blocks_for_chr(chr_max):
                block_n += 1
                block_sub = sub[(sub["POS"] >= start) & (sub["POS"] <= end)]
                if len(block_sub) < 30:
                    continue
                rows.append({
                    "Block": block_n,
                    "Chrom": chrom_n,
                    "StartSnpIdx": idx_global,
                    "StartSnpID": block_sub["ID"].iloc[0],
                    "EndSnpIdx": idx_global + len(block_sub) - 1,
                    "EndSnpID": block_sub["ID"].iloc[-1],
                    "NumSnps": len(block_sub),
                })
                idx_global += len(block_sub)
        info = pd.DataFrame(rows)
        info.to_csv(SBAYES_DIR / "ldm.info.preview.tsv", sep="\t", index=False)
        print(f"  wrote {SBAYES_DIR}/ldm.info.preview.tsv ({len(info)} blocks)")
        print(f"  total markers across blocks: {info['NumSnps'].sum():,}")
        print(f"  mean markers per block: {info['NumSnps'].mean():,.0f}")
        print(f"  Estimated wall-clock at 10 min/block: {10*len(info)/60:.0f} hours")
        return

    if args.run_trait:
        print(f"[Path B] sbayesrc() on trait {args.run_trait}. Pending LD reference.")
        return

    if args.collect:
        print("[Path B] Collect SBayesRC PIPs at 41 fine-mapped loci. Pending per-trait runs.")
        return


if __name__ == "__main__":
    main()
