"""Generate paper-ready LaTeX tables and Markdown summaries from the grain
fine-mapping outputs.

Outputs:
  paper/finemapping_v1/tables/grain_table_s7_recovery.tex
  paper/finemapping_v1/tables/grain_table_s8_per_locus.tex
  data/rice_3k/results/grain_finemap/grain_per_locus_table.tsv
  data/rice_3k/results/grain_gwas/grain_table_s5_addendum.tex   (4-row addendum)
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

DATA = Path("/mnt/data/GraphGWAS/data/rice_3k")
RES = DATA / "results"
GWAS_OUT = RES / "grain_gwas"
FM_OUT = RES / "grain_finemap"
PAPER_TABLES = Path("/mnt/data/GraphGWAS/paper/finemapping_v1/tables")
PAPER_TABLES.mkdir(parents=True, exist_ok=True)

METHODS = ["GAFM", "HBP", "GAFM-MX", "HBP-MX", "ENS",
           "SuSiE", "SuSiE-inf", "FINEMAP-inf", "SBayesRC"]
TRAITS = ["TGW", "GL", "GW", "RLW"]


def _esc(s: str) -> str:
    """Escape LaTeX special chars for table text."""
    return (str(s).replace("&", r"\&").replace("%", r"\%")
            .replace("_", r"\_").replace("#", r"\#"))


def table_s5_addendum():
    summary = pd.read_csv(GWAS_OUT / "grain_gwas_summary.tsv", sep="\t")
    rows = []
    for trait in TRAITS:
        sub = summary[summary["trait"] == trait]
        if sub.empty:
            continue
        r = sub.iloc[0]
        rows.append(
            f"{trait}                & {int(r['N_variants']):>9,} & {r['lambda_gc']:>5.2f} "
            f"& ${r['min_p']:.2e}$".replace("e", r"\times10^{").replace("$\\", "$")
        )
    # Custom-escape the scientific notation
    out_rows = []
    for trait in TRAITS:
        sub = summary[summary["trait"] == trait]
        if sub.empty:
            continue
        r = sub.iloc[0]
        # scientific format
        p = r["min_p"]
        if p > 0:
            from math import log10, floor
            mantissa = p / (10 ** floor(log10(p)))
            exp = int(floor(log10(p)))
            p_tex = f"${mantissa:.1f}\\times10^{{{exp}}}$"
        else:
            p_tex = "$\\sim 0$"
        out_rows.append(
            f"{trait:<6s}            & {int(sub.iloc[0]['n_indep_gw_leads']):>4d} & "
            f"{r['lambda_gc']:>5.2f} & {p_tex} & {int(r['n_indep_gw_leads']):>5d} \\\\"
        )
    tex = []
    tex.append("% Auto-generated by tests/rice3k_grain_shape_paper_tables.py")
    tex.append("% 4-row addendum for Table S5 (IRRI 18-trait scan): grain weight + shape rerun")
    tex.append(r"\begin{table}[htbp]")
    tex.append(r"\centering\small")
    tex.append(r"\caption{\textbf{3kRG grain weight + shape whole-genome scan summary "
               r"(Niu \emph{et al.}\ 2021 phenotype reference panel).} Same plink2 "
               r"\texttt{--glm linear} pipeline as Table~S5, with PC1--PC10 covariates from "
               r"\texttt{rice\_3k.psam}. Niu \emph{et al.}\ 2021 \cite{niu2021grain} reports "
               r"21 stable QTNs from a compressed-MLM analysis on the same panel; we recover "
               r"\textbf{20 of 21} (95\%) within 100\,kb of an independent lead at $p\leq5\times10^{-8}$. "
               r"The fourth $\lambda_{GC}$ value is elevated above the 1.0 null ($\lambda_{GC} > 1.4$ "
               r"for all four traits) under PC1--PC10 correction; this matches the IRRI scan and "
               r"reflects the well-documented XI/GJ subpopulation structure ($F_{ST}\approx 0.5$).}")
    tex.append(r"\label{tab:sup_grain_scan}")
    tex.append(r"\begin{tabular}{lrrrr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Trait} & \textbf{N indep.\ leads} & $\lambda_{GC}$ & \textbf{min}~$p$ "
               r"& \textbf{Niu QTN match} \\")
    tex.append(r"\midrule")
    # Niu QTN match counts (from grain_niu2021_match.tsv)
    match_df = pd.read_csv(GWAS_OUT / "grain_niu2021_match.tsv", sep="\t")
    for trait in TRAITS:
        sub = summary[summary["trait"] == trait]
        if sub.empty:
            continue
        r = sub.iloc[0]
        p = r["min_p"]
        from math import log10, floor
        if p > 0:
            mantissa = p / (10 ** floor(log10(p)))
            exp = int(floor(log10(p)))
            p_tex = f"${mantissa:.1f}\\times10^{{{exp}}}$"
        else:
            p_tex = "$\\sim 0$"
        m_sub = match_df[match_df["trait"] == trait]
        n_match = int(m_sub["matched"].sum())
        n_qtn = len(m_sub)
        tex.append(f"{trait}    & {int(r['n_indep_gw_leads']):>5d} & {r['lambda_gc']:>5.2f} "
                   f"& {p_tex:>26s} & {n_match}/{n_qtn} \\\\")
    tex.append(r"\midrule")
    tex.append(r"\textbf{Total} &       &       &  & "
               f"\\textbf{{{int(match_df['matched'].sum())}/{len(match_df)}}} \\\\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")
    out = GWAS_OUT / "grain_table_s5_addendum.tex"
    out.write_text("\n".join(tex))
    print(f"Wrote {out}")


def table_s7_recovery():
    """Per-method recovery scorecard (Niu Tier 1, Niu Tier 2, Ren Tier 3)."""
    sc_path = FM_OUT / "grain_recovery_scorecard.tsv"
    if not sc_path.exists():
        print(f"  skip (no {sc_path.name})")
        return
    sc = pd.read_csv(sc_path, sep="\t")
    tex = []
    tex.append("% Auto-generated by tests/rice3k_grain_shape_paper_tables.py")
    tex.append(r"\begin{table}[htbp]")
    tex.append(r"\centering\small")
    tex.append(r"\caption{\textbf{Three-tier ground-truth recovery on the 3kRG grain "
               r"weight + shape rerun.} All six methods fine-map the same 41 leads "
               r"(top 5 GW-significant + top 2 suggestive per trait, plus 13 Niu-augment leads; "
               r"$\pm$100\,kb windows, 95\% credible sets). \emph{Tier 1:} variant-level recovery of the 21 stable "
               r"QTNs reported in Niu \emph{et al.}\ 2021 \cite{niu2021grain}, scored as the "
               r"QTN's chr:pos appearing in the 95\% credible set of any locus assigned to the "
               r"matching trait. \emph{Tier 2:} locus-level recovery of the 7 NEW candidate "
               r"genes flagged by Niu \emph{et al.}\ 2021 (anchor: candidate-gene QTN coordinate "
               r"covered by the credible set). \emph{Tier 3:} gene-level recovery against the "
               r"Ren \emph{et al.}\ 2023 \cite{ren2023rice} grain-quality catalogue (104 grain-size "
               r"+ grain-shape genes), scored as the gene falling within $\pm$250\,kb of the "
               r"top-PIP variant of any matching-trait locus.}")
    tex.append(r"\label{tab:sup_grain_recovery}")
    tex.append(r"\begin{tabular}{lrrrr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Method} & \shortstack[r]{\textbf{Tier 1}\\\textbf{Niu QTN}\\\textbf{(in CS)}} "
               r"& \shortstack[r]{\textbf{Tier 1}\\\textbf{Niu QTN}\\\textbf{top-1 PIP}} "
               r"& \shortstack[r]{\textbf{Tier 2}\\\textbf{NEW gene}\\\textbf{(locus)}} "
               r"& \shortstack[r]{\textbf{Tier 3}\\\textbf{Ren genes}\\\textbf{(±250\,kb)}} \\")
    tex.append(r"\midrule")
    for _, r in sc.iterrows():
        m = r["method"]
        t1 = f"{int(r['tier1_qtns_in_cs'])}/{int(r['tier1_qtns_total'])} ({r['tier1_recovery_pct']:.0f}\\%)"
        t1top = f"{int(r['tier1_top1_count'])}/{int(r['tier1_qtns_total'])}"
        t2 = f"{int(r['tier2_novel_recovered'])}/{int(r['tier2_novel_total'])} ({r['tier2_recovery_pct']:.0f}\\%)"
        t3 = f"{int(r['tier3_ren_genes_recovered'])}"
        tex.append(f"{m:<14s} & {t1:>14s} & {t1top:>10s} & {t2:>14s} & {t3:>5s} \\\\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")
    out = PAPER_TABLES / "grain_table_s7_recovery.tex"
    out.write_text("\n".join(tex))
    print(f"Wrote {out}")


def table_s8_per_locus():
    fm_path = FM_OUT / "grain_finemap_summary.tsv"
    if not fm_path.exists():
        print(f"  skip (no {fm_path.name})")
        return
    df = pd.read_csv(fm_path, sep="\t")

    # pivot: rows = (trait, lead) ; columns = method ; cells = "CS_size / topPIP"
    df["cs_size"] = pd.to_numeric(df["cs_size"], errors="coerce")
    df["top_pip"] = pd.to_numeric(df["top_pip"], errors="coerce")
    df["cell"] = df.apply(
        lambda r: ("--" if pd.isna(r["cs_size"]) else f"{int(r['cs_size'])}")
        + ("" if pd.isna(r["top_pip"]) else f"/{r['top_pip']:.2f}"),
        axis=1,
    )
    # Keep all 9 methods in the dataframe for completeness, but Table S8 only
    # displays a curated 5-method subset (best-of-each-class) to fit the page.
    DISPLAY_METHODS = ["GAFM-MX", "HBP-MX", "ENS", "SuSiE", "SBayesRC"]
    pivot_full = (
        df.pivot_table(index=["trait", "lead_chr", "lead_pos", "lead_p", "n_variants"],
                       columns="method", values="cell", aggfunc="first")
        .reindex(columns=METHODS)
        .reset_index()
    )
    pivot_full = pivot_full.sort_values(["trait", "lead_p"]).reset_index(drop=True)
    pivot = pivot_full[["trait", "lead_chr", "lead_pos", "lead_p", "n_variants"] + DISPLAY_METHODS]

    tex = []
    tex.append("% Auto-generated by tests/rice3k_grain_shape_paper_tables.py")
    tex.append(r"\begin{table}[htbp]")
    tex.append(r"\centering\footnotesize")
    tex.append(r"\setlength{\tabcolsep}{4pt}")
    tex.append(r"\caption{\textbf{Per-locus credible-set comparison on the 3kRG grain "
               r"weight + shape rerun (v0.1.5).} Cells report 95\% credible-set size / "
               r"top-variant PIP. We display the curated 5-method best-of-class subset; "
               r"the full 9-method comparison (GAFM, HBP, GAFM-MX, HBP-MX, ENS, SuSiE, "
               r"SuSiE-inf, FINEMAP-inf, SBayesRC) is in "
               r"\texttt{data/rice\_3k/results/grain\_finemap/grain\_finemap\_summary.tsv}. "
               r"All methods receive $\lambda_{GC}$-deflated z-scores (z $\to$ z/$\sqrt{\lambda_{GC}}$). "
               r"Loci selected as the top 5 GW-significant + top 2 suggestive per trait, "
               r"plus 13 leads matched within $\pm$100\,kb of a Niu 2021 QTN. "
               r"$N_v$ is the number of variants in the $\pm$100\,kb fine-map window.}")
    tex.append(r"\label{tab:sup_grain_per_locus}")
    tex.append(r"\begin{tabular}{l l r r r r r r r}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Trait} & \textbf{Locus} & \textbf{lead $p$} & $N_v$ "
               r"& \textbf{GAFM-MX} & \textbf{HBP-MX} & \textbf{ENS} "
               r"& \textbf{SuSiE} & \textbf{SBayesRC} \\")
    tex.append(r"\midrule")
    cur_trait = None
    for _, r in pivot.iterrows():
        trait = r["trait"]
        loc = f"{r['lead_chr']}:{int(r['lead_pos']):,}"
        from math import log10, floor
        p = r["lead_p"]
        if p > 0 and p < 1:
            mantissa = p / (10 ** floor(log10(p)))
            exp = int(floor(log10(p)))
            p_tex = f"${mantissa:.1f}{{\\times}}10^{{{exp}}}$"
        else:
            p_tex = f"${p:.2g}$"
        nv = int(r["n_variants"])
        if trait != cur_trait:
            tex.append(rf"\addlinespace[0.5ex]")
        cur_trait = trait
        cells = []
        for m in DISPLAY_METHODS:
            v = r.get(m, "--")
            if pd.isna(v):
                v = "--"
            cells.append(_esc(v))
        tex.append(f"{trait} & {loc} & {p_tex} & {nv} & "
                   + " & ".join(cells) + r" \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")
    out = PAPER_TABLES / "grain_table_s8_per_locus.tex"
    out.write_text("\n".join(tex))
    pivot.to_csv(FM_OUT / "grain_per_locus_table.tsv", sep="\t", index=False)
    print(f"Wrote {out}")
    print(f"Wrote {FM_OUT}/grain_per_locus_table.tsv")


def main():
    print("Table S5 addendum (4 grain traits):")
    table_s5_addendum()
    print("\nTable S7 (recovery scorecard):")
    table_s7_recovery()
    print("\nTable S8 (per-locus method comparison):")
    table_s8_per_locus()


if __name__ == "__main__":
    main()
